#@data/values-schema
---
#! MYSQL
mysql:
  enabled: false
  version: 9.1.1

  helm:
    architecture: standalone
    metrics:
      enabled: false
      #@schema/type any=True
      extraEnvVars: []
    image:
      debug: false
      pullPolicy: IfNotPresent
      tag: 8.0.29-debian-10-r23
    auth:
      database:	svc
      username:	svc
      existingSecret: svc-mysql
    primary:
      persistence:
        enabled: true
        size: 4Gi
      #@schema/type any=True
      extraEnvVars: []

#! POSTGRES
postgres:
  enabled: false
  version: 11.5.0

  helm:
    architecture: standalone
    metrics:
      enabled: false
      #@schema/type any=True
      extraEnvVars: []
    image:
      debug: false
      pullPolicy: IfNotPresent
      tag: 14.1.0-debian-10-r80
    auth:
      database:	svc
      username:	svc
      existingSecret: svc-postgres
    primary:
      persistence:
        enabled: true
        size: 4Gi
      #@schema/type any=True
      extraEnvVars: []
