#@data/values-schema
---
repository: acm-svc-acme

#! MYSQL
mysql:
  enabled: false
  version: 9.1.7
  chart: bitnami/mysql
  values:
    architecture: standalone
    auth:
      database:	svc
      username:	svc
    image:
      debug: false
      pullPolicy: IfNotPresent
    metrics:
      enabled: false
      #@schema/type any=True
      extraEnvVars: []
    primary:
      affinity: {}
      nodeSelector: {}
      #@schema/type any=True
      extraEnvVars: []
      persistence:
        enabled: true
        size: 2Gi
        storageClass: ""
      resources:
        limits: {}
        requests: {}

#! POSTGRES
postgres:
  enabled: false
  version: 11.6.6
  chart: bitnami/postgresql
  values:
    architecture: standalone
    auth:
      database:	svc
      username:	svc
    image:
      debug: false
      pullPolicy: IfNotPresent
    metrics:
      enabled: false
      #@schema/type any=True
      extraEnvVars: []
    primary:
      affinity: {}
      nodeSelector: {}
      #@schema/type any=True
      extraEnvVars: []
      persistence:
        enabled: true
        size: 2Gi
        storageClass: ""
      resources:
        limits: {}
        requests: {}

#! RABBITMQ
rabbitmq:
  enabled: false
  version: 10.1.7
  chart: bitnami/rabbitmq
  values:
    affinity: {}
    auth:
      username:	svc
    clustering:
      enabled: false
    #@schema/type any=True
    extraEnvVars: []
    image:
      debug: false
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
    metrics:
      enabled: false
    nodeSelector: {}
    persistence:
      enabled: true
      size: 2Gi
      storageClass: ""
    resources:
      limits: {}
      requests: {}
    serviceAccount:
      create: false

#! ELASTICSEARCH
elasticsearch:
  enabled: false
  version: 18.2.12
  chart: bitnami/elasticsearch
  values:
    coordinating:
      affinity: {}
      nodeSelector: {}
      replicaCount: 1
    curator:
      enabled: false
      affinity: {}
      nodeSelector: {}
      replicaCount: 1
    data:
      affinity: {}
      nodeSelector: {}
      replicaCount: 1
      persistence:
        enabled: true
        size: 2Gi
        storageClass: ""
    #@schema/type any=True
    extraEnvVars: []
    image:
      debug: false
      pullPolicy: IfNotPresent
    ingest:
      affinity: {}
      nodeSelector: {}
      replicaCount: 1
    ingress:
      enabled: false
    metrics:
      enabled: false
    master:
      affinity: {}
      nodeSelector: {}
      replicaCount: 1
      persistence:
        enabled: true
        size: 2Gi
        storageClass: ""
      resources:
        limits: {}
        requests: {}

#! REDIS
redis:
  enabled: false
  version: 16.12.1
  chart: bitnami/redis
  values:
    architecture: standalone
    auth:
      enabled: false
    #@schema/type any=True
    extraEnvVars: []
    image:
      debug: false
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
    metrics:
      enabled: false
    master:
      affinity: {}
      nodeSelector: {}
      persistence:
        enabled: false
        size: 2Gi
        storageClass: ""
      resources:
        limits: {}
        requests: {}

#! NATS
nats:
  enabled: false
  version: 7.3.5
  chart: bitnami/nats
  values:
    affinity: {}
    nodeSelector: {}
    auth:
      enabled: false
    #@schema/type any=True
    extraEnvVars: []
    image:
      debug: false
      pullPolicy: IfNotPresent
    metrics:
      enabled: false
    resources:
      limits: {}
      requests: {}

#! ETCD
etcd:
  enabled: false
  version: 8.3.0
  chart: bitnami/etcd
  values:
    affinity: {}
    nodeSelector: {}
    auth:
      rbac:
        create: false
    #@schema/type any=True
    extraEnvVars: []
    image:
      debug: false
      pullPolicy: IfNotPresent
    metrics:
      enabled: false
    persistence:
      enabled: false
      size: 2Gi	
      storageClass: ""
    resources:
      limits: {}
      requests: {}
