#@data/values-schema
---
repository: acm-svc-acme

#! MYSQL
mysql:
  enabled: false
  version: 9.1.1
  chart: bitnami/mysql
  values:
    architecture: standalone
    auth:
      database:	svc
      username:	svc
    image:
      debug: false
      pullPolicy: IfNotPresent
      tag: 8.0.29-debian-10-r23
    metrics:
      enabled: false
      #@schema/type any=True
      extraEnvVars: []
    primary:
      #@schema/type any=True
      extraEnvVars: []
      persistence:
        enabled: true
        size: 4Gi
      resources:
        limits: {}
        requests: {}

#! POSTGRES
postgres:
  enabled: false
  version: 11.5.0
  chart: bitnami/postgresql
  values:
    architecture: standalone
    auth:
      database:	svc
      username:	svc
    image:
      debug: false
      pullPolicy: IfNotPresent
      tag: 14.1.0-debian-10-r80
    metrics:
      enabled: false
      #@schema/type any=True
      extraEnvVars: []
    primary:
      #@schema/type any=True
      extraEnvVars: []
      persistence:
        enabled: true
        size: 4Gi
      resources:
        limits: {}
        requests: {}

#! RABBITMQ
rabbitmq:
  enabled: false
  version: 10.1.7
  chart: bitnami/rabbitmq
  values:
    auth:
      username:	svc
    clustering:
      enabled: false
    #@schema/type any=True
    extraEnvVars: []
    image:
      debug: false
      pullPolicy: IfNotPresent
      tag: 3.10.2-debian-10-r7
    ingress:
      enabled: false
    metrics:
      enabled: false
    persistence:
      enabled: true
      storageClass: ""
      size: 4Gi
    resources:
      limits: {}
      requests: {}
    serviceAccount:
      create: false

#! ELASTICSEARCH
elasticsearch:
  enabled: false
  version: 18.2.9
  chart: bitnami/elasticsearch
  values:
    coordinating:
      replicaCount: 1
    data:
      replicaCount: 1
      persistence:
        enabled: true
        storageClass: ""
        size: 4Gi
    #@schema/type any=True
    extraEnvVars: []
    image:
      debug: false
      pullPolicy: IfNotPresent
      tag: 8.2.2-debian-10-r0
    ingest:
      replicaCount: 1
    ingress:
      enabled: false
    metrics:
      enabled: false
    master:
      persistence:
        enabled: true
        storageClass: ""
        size: 4Gi
      resources:
        limits: {}
        requests: {}

#! REDIS
redis:
  enabled: false
  version: 16.12.1
  chart: bitnami/redis
  values:
    architecture: standalone
    auth:
      enabled: false
    #@schema/type any=True
    extraEnvVars: []
    image:
      debug: false
      pullPolicy: IfNotPresent
      tag: 6.2.7-debian-11-r0
    ingress:
      enabled: false
    metrics:
      enabled: false
    master:
      persistence:
        enabled: false
      resources:
        limits: {}
        requests: {}
