#@data/values-schema
---
#! global
ecosystem: acm
organization: acme
containerRegistry: ghcr.io
repository: acm-svc-repository
environment: dev
tag: latest

#! features
features:
  enableLinkerd: false

#! environment
#@schema/type any=True
env: []
#@schema/type any=True
envFromSecrets: []
#@schema/type any=True
envFromConfigMaps: []
#@schema/type any=True
envFromDependencies: []

#! k8s resources
namespace:
  labels: {}
  annotations: {}

deployment:
  enable: true
  replicas: 1
  name: svc
  port: 8000
  labels: {}
  annotations: {}
  resources: {}
  imagePullSecrets: false

  templateLabels: {}
  matchLabels: 
    overwrite: false
    labels: {}

ingress:
  enable: false
  name: svc
  type: alb
  domain:
    enable: false
    name: acme.io

  alb:
    certificateArn: secret

#! pipeline control
pipelineControl:
  datetime: 'today'
  environmentsAsNamespaces: false
