#@data/values-schema

---
ecosystem: acm
organization: acme
containerRegistry: ghcr.io
repository: acm-svc-repository
environment: dev
tag: latest

features:
  enableLinkerd: true

namespace:
  enable: true
  labels: {}
  annotations: {}

deployment:
  enable: true
  replicas: 1
  name: svc
  port: 80
  labels: {}
  annotations: {}
  resources: {}

  templateLabels: {}
  matchLabels: 
    overwrite: false
    labels: {}

ingress:
  enable: false
  name: svc
  type: alb
  domain: ff.io

  alb:
    certificateArn: secret
