#@data/values-schema
---
#! global
ecosystem: acm
organization: acme
containerRegistry: ghcr.io
repository: acm-svc-repository
environment: dev
tag: latest

#! features
features:
  enableLinkerd: false

#! k8s resources
namespace:
  enable: true
  labels: {}
  annotations: {}

deployment:
  enable: true
  replicas: 1
  name: svc
  port: 80
  labels: {}
  annotations: {}
  resources: {}

  templateLabels: {}
  matchLabels: 
    overwrite: false
    labels: {}

ingress:
  enable: false
  name: svc
  type: alb
  domain: acme.io

  alb:
    certificateArn: secret

#! pipeline control
pipelineControl:
  datetime: 'today'
  dockerconfigjson: {}
