repos:
  - repo: local
    hooks:
      - id: simple-pylint
        name: simple-pylint
        entry: npm
        args: ["run", "build"]
        language: system
        types: [javascript]
        pass_filenames: false

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.7
    hooks:
      - id: gitleaks
