repos:
  - repo: local
    hooks:
      - id: build-actions
        name: Build Actions
        entry: npm
        args: ["run", "build"]
        language: system
        types: ['javascript']
        pass_filenames: false

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.7
    hooks:
      - id: gitleaks
