name: "Pipeline Config Scrapper"
description: "Analize current event trigger and indicates paths and configs"

inputs:
  writeSummary:
    required: true
    default: "false"
    description: ""
  containerRegistry:
    required: false
    default: ghcr.io
    description: "Container registry to upload container images"

outputs:
  actor:
    description: ""
  commiter_name:
    description: ""
  commiter_email:
    description: ""
  commiter_username:
    description: ""
  deploy_tag:
    description: ""
  deploy_tags:
    description: ""
  event:
    description: ""
  environment:
    description: ""
  feature_has_dockerfile:
    description: ""
  feature_has_dockerignore:
    description: ""
  feature_has_releaserc:
    description: ""
  language:
    description: ""

runs:
  using: "node16"
  main: "index.js"
