#@ load("@ytt:data", "data")

#@ if data.values.ingress.enable:
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: #@ data.values.service.name

  #@  ingressAnnotations = {}
  #@  if data.values.ingress.tls.enable:
  #@    ingressAnnotations.update({
  #@      "kubernetes.io/ingress.class": data.values.ingress.type,
  #@    })
  #@
  #@    if data.values.ingress.tls.letsencrypt.enable:
  #@      ingressAnnotations.update({ "cert-manager.io/" + data.values.ingress.tls.letsencrypt.type: "letsencrypt-" + data.values.environment })
  #@    end
  #@
  #@    if data.values.ingress.type == "alb":
  #@      ingressAnnotations.update({
  #@        "alb.ingress.kubernetes.io/target-type": "instance",
  #@        "alb.ingress.kubernetes.io/scheme": "internet-facing",
  #@        "alb.ingress.kubernetes.io/success-codes": "200-399",
  #@        "alb.ingress.kubernetes.io/ssl-redirect": "443",
  #@        "alb.ingress.kubernetes.io/ssl-policy": "ELBSecurityPolicy-2016-08",
  #@        "alb.ingress.kubernetes.io/group.name": data.values.ecosystem,
  #@        "alb.ingress.kubernetes.io/load-balancer-name": data.values.ecosystem,
  #@        "alb.ingress.kubernetes.io/certificate-arn": data.values.ingress.alb.certificateArn,
  #@        "alb.ingress.kubernetes.io/load-balancer-attributes": "idle_timeout.timeout_seconds=1200",
  #@        "alb.ingress.kubernetes.io/healthcheck-interval-seconds": "300",
  #@        "alb.ingress.kubernetes.io/listen-ports": '[{"HTTPS": 443}]',
  #@      })
  #@    end
  #@  end
  annotations: #@ ingressAnnotations

spec:

  #@ if data.values.ingress.tls.enable:
  tls:
    - secretName: #@ "cert-" + data.values.repository
      #@ if data.values.ingress.tls.removeEnvironmentPrefix:
      hosts:
       - #@ "{}.{}".format(data.values.repository, data.values.ingress.tls.domain)
      #@ else:
      hosts:
       - #@ "{}.{}.{}".format(data.values.repository, data.values.environment, data.values.ingress.tls.domain)
      #@ end
  #@ end

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: #@ data.values.deployment.name
                port:
                  number: #@ data.values.port
      #@  if data.values.ingress.tls.enable:
        #@  if data.values.ingress.tls.removeEnvironmentPrefix:
      host: #@ "{}.{}".format(data.values.repository, data.values.ingress.tls.domain)
        #@  else:
      host: #@ "{}.{}.{}".format(data.values.repository, data.values.environment, data.values.ingress.tls.domain)
        #@  end
      #@  end


#@  if data.values.ingress.type == "traefik":
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: #@ data.values.service.name
spec:
  entryPoints:
    - web
  routes:
    - match: #@ "Host(`{}.{}.{}`)".format(data.values.repository, data.values.environment, data.values.ingress.tls.domain)
      kind: Rule
      services:
        - name: #@ data.values.service.name
          port:  #@ data.values.port
#@  end
#@  end