#@ load("@ytt:data", "data")

---
#@ if data.values.deployment.enable:
#@ if data.values.deployment.hpa.enable:
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: #@ data.values.service.name
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: #@ data.values.service.name
  minReplicas: #@ data.values.deployment.hpa.minReplicas
  maxReplicas: #@ data.values.deployment.hpa.maxReplicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: #@ data.values.deployment.hpa.cpu
#@ end
#@ end
