#@ load("@ytt:data", "data")

#@ def ListToMap (listOfMaps):
#@    newMap = {}
#@    for i in range(len(listOfMaps)):
#@        newMap.update({ listOfMaps[i].name: listOfMaps[i].value })
#@    end
#@    return newMap
#@ end
---
#@ if data.values.cronjob.enable:
apiVersion: batch/v1
kind: CronJob

metadata:
  name: #@ data.values.cronjob.name
  labels: #@ data.values.cronjob.labels
  annotations: #@ data.values.cronjob.annotations

spec:
  schedule: #@ data.values.cronjob.schedule

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never

          #@ if/end data.values.deployment.imagePullSecrets:
          imagePullSecrets:
            - name: #@ data.values.deployment.imagePullSecretsName

          containers:
          - name: #@ data.values.cronjob.name
            image: #@ "{}/{}/{}:{}".format(data.values.containerRegistry, data.values.organization, data.values.repository, data.values.tag)
            command: #@ data.values.cronjob.command

            #@  cronjobResources = {
            #@    "limits": ListToMap(data.values.cronjob.resources.limits),
            #@    "requests": ListToMap(data.values.cronjob.resources.requests),
            #@  }
            resources: #@ cronjobResources

            #@ cronjobEnvs = []
            #@ cronjobEnvs.extend(data.values.env)
            
            #@ for i in data.values.envFromConfigMaps:
            #@   cronjobEnvs.extend([{ 
            #@    "name": i, 
            #@    "valueFrom": {
            #@      "configMapKeyRef": {
            #@        "name": data.values.repository,
            #@        "key": i,
            #@      }
            #@    }
            #@   }])
            #@ end
            
            #@ for i in data.values.envFromSecrets:
            #@   cronjobEnvs.extend([{ 
            #@    "name": i, 
            #@    "valueFrom": {
            #@      "secretKeyRef": {
            #@        "name": data.values.repository,
            #@        "key": i,
            #@      }
            #@    }
            #@   }])
            #@ end
            
            #@ for i in data.values.envFromDependencies:
            #@   cronjobEnvs.extend([{ 
            #@    "name": (i + "_connection_string").upper(),
            #@    "valueFrom": {
            #@      "secretKeyRef": {
            #@        "name": "dep-secret-" + i,
            #@        "key": "connection-string",
            #@      }
            #@    }
            #@   }])
            #@ end
            env: #@ cronjobEnvs
#@ end
