name: self
on: [ push ]

jobs:

  Analysis:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:

      # pre-job
      - name: Setup | Cloning repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      #job
      - name: Run GitLeaks
        uses: docker://opendevsecops/gitleaks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --repo=https://github.com/${{github.repository}} 

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Upload sarif file
        uses: github/codeql-action/upload-sarif@v1
        with:
          category: ${{ env.GITHUB_SHA }}


  Release:
    runs-on: ubuntu-latest
    needs: Analysis

    steps:

      - name: Cloning repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm i -g -D \
            semantic-release \
            @semantic-release/git \
            @semantic-release/github \
            @semantic-release/changelog \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator
          semantic-release
