name: service

on:
  workflow_call:
    outputs:
      NoLanguageDetected: 
        description: "Checks if a language is detected"
        value: ${{ jobs.Setup.outputs.NoLanguageDetected }}
      RepositoryIsNode:
        description: "Checks if the repository is a Node.js repository"
        value: ${{ jobs.Setup.outputs.RepositoryIsNode }}
      RepositoryIsPython:
        description: "Checks if the repository is a Python repository"
        value: ${{ jobs.Setup.outputs.RepositoryIsPython }}

jobs:

  Setup:
    runs-on: ubuntu-latest

    outputs:
      NoLanguageDetected: "${{ steps.check_else_write.outputs.answer }}"
      RepositoryIsNode: ${{ steps.check_node_write.outputs.answer }}
      RepositoryIsPython: ${{ steps.check_python_write.outputs.answer }}

    steps:
      - uses: actions/checkout@v3

      # nodejs
      - name: Check if Node repository
        id: check_node
        uses: andstor/file-existence-action@v1
        with:
          files: "package.json"

      - name: Update with Node reference
        id: check_node_write
        if: steps.check_node.outputs.files_exists == 'true'
        run: echo "::set-output name=answer::true"

      # python
      - name: Check if python repository
        id: check_python
        uses: andstor/file-existence-action@v1
        with:
          files: "requirements.txt, **/*.py"

      - name: Update with Python reference
        id: check_python_write
        if: steps.check_python.outputs.files_exists == 'true'
        run: echo "::set-output name=answer::true"

      # else
      - name: Update with undefined reference
        id: check_else_write
        if: |
          always()
          && steps.check_node.outputs.files_exists == 'false'
          && steps.check_python.outputs.files_exists == 'false'
        run: echo "::set-output name=answer::true"


  Install-Node:
    runs-on: ubuntu-latest
    needs: Setup
    if: needs.Setup.outputs.RepositoryIsNode == 'true'
    
    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x]
    
    steps:
      - uses: actions/checkout@v3

      - name: Check yarn.lock
        id: check_yarn_lock
        uses: andstor/file-existence-action@v1
        with:
          files: "yarn.lock"

      - name: Check package.lock
        id: check_package_lock
        uses: andstor/file-existence-action@v1
        with:
          files: "package.lock"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        if: steps.check_yarn_lock.outputs.files_exists == 'true'
        run: yarn

      - name: npm ci
        if: steps.check_package_lock.outputs.files_exists == 'true'
        run: npm ci

      - name: npm install
        if: |
          always()
          && steps.check_yarn_lock.outputs.files_exists == 'false'
          && steps.check_package_lock.outputs.files_exists == 'false'
        run: npm install

      - run: npm run lint --if-present

      - run: npm run test --if-present

      - run: npm run build --if-present

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}


  Install-Python:
    runs-on: ubuntu-latest
    needs: Setup
    if: needs.Setup.outputs.RepositoryIsPython == 'true'

    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    
    steps:
      - uses: actions/checkout@v3

      - name: Pip install
        run: pip install -r requirements.txt
