name: service

on:
  workflow_call:
    inputs:
      type:
        type: string
        required: false
        default: service
      containerRegistry:
        type: string
        required: true
        default: ghcr.io
      mysqlEnabled:
        type: boolean
        required: false
        default: false
    
    outputs:
      NoLanguageDetected: 
        description: "Checks if a language is detected"
        value: ${{ jobs.Setup.outputs.NoLanguageDetected }}
      RepositoryIsNode:
        description: "Checks if the repository is a Node.js repository"
        value: ${{ jobs.Setup.outputs.RepositoryIsNode }}
      RepositoryIsPython:
        description: "Checks if the repository is a Python repository"
        value: ${{ jobs.Setup.outputs.RepositoryIsPython }}

jobs:

  Setup:
    runs-on: ubuntu-latest

    outputs:
      # globals
      Branch: ${{ steps.commit_data.outputs.branch }}
      ShaHash: ${{ steps.commit_data.outputs.sha_short }}
      Date: ${{ steps.commit_data.outputs.date }}
      Timestamp: ${{ steps.commit_data.outputs.timestamp }}
      # repository-wise
      NoLanguageDetected: "${{ steps.check_else_write.outputs.answer }}"
      RepositoryIsNode: ${{ steps.check_node_write.outputs.answer }}
      RepositoryIsPython: ${{ steps.check_python_write.outputs.answer }}

    steps:
      - name: Cloning repository
        uses: actions/checkout@v3
      
      - name: Cloning tools
        uses: actions/checkout@v3
        with:
          ref: main
          path: .ff
          repository: filipeforattini/ff-iac-github-actions

      # setup
      - name: Pipeline setup
        uses: actions/github-script@v6
        id: script_setup
        with:
          result-encoding: string
          script: return require('./.ff/scripts/steps/setup')({ context })

      # get commit hash
      - name: PRINT SETUP
        env:
          PIPELINE_SETUP: ${{ steps.script_setup.outputs.result}}
        run: |
          echo all = $PIPELINE_SETUP
          echo branch = $(echo $PIPELINE_SETUP | jq -r '.git.branch')

      # get commit hash
      - name: Get commit hash
        id: commit_data
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo "::set-output name=timestamp::$(date +%s)"

      # language nodejs
      - name: Check if Node repository
        id: check_node
        uses: andstor/file-existence-action@v1
        with:
          files: "package.json"

      - name: Update with Node reference
        id: check_node_write
        if: steps.check_node.outputs.files_exists == 'true'
        run: echo "::set-output name=answer::true"

      # language python
      - name: Check if python repository
        id: check_python
        uses: andstor/file-existence-action@v1
        with:
          files: "requirements.txt"

      - name: Update with Python reference
        id: check_python_write
        if: steps.check_python.outputs.files_exists == 'true'
        run: echo "::set-output name=answer::true"

      # language else
      - name: Update with undefined reference
        id: check_else_write
        if: |
          always()
          && steps.check_node.outputs.files_exists == 'false'
          && steps.check_python.outputs.files_exists == 'false'
        run: echo "::set-output name=answer::true"


  Build-Node:
    runs-on: ubuntu-latest
    needs: Setup
    if: |
      github.event_name == 'push'
      && needs.Setup.outputs.RepositoryIsNode == 'true'

    strategy:
      matrix:
        node-version: [16, 17]
    
    steps:
      - uses: actions/checkout@v3

      # checks
      - name: Check yarn.lock
        id: check_yarn_lock
        uses: andstor/file-existence-action@v1
        with:
          files: "yarn.lock"

      - name: Check package.lock
        id: check_package_lock
        uses: andstor/file-existence-action@v1
        with:
          files: "package.lock"

      # install node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # load caches
      - name: Load cache from yarn.lock
        uses: actions/cache@v2
        if: steps.check_yarn_lock.outputs.files_exists == 'true'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Load cache from package.json
        uses: actions/cache@v2
        if: steps.check_package_lock.outputs.files_exists == 'true'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.lock') }}
          
      # install dependencies
      - name: Install dependencies with yarn install
        if: steps.check_yarn_lock.outputs.files_exists == 'true'
        run: yarn

      - name: Install dependencies with npm ci
        if: steps.check_package_lock.outputs.files_exists == 'true'
        run: npm ci

      - name: Install dependencies with npm install
        if: |
          always()
          && steps.check_yarn_lock.outputs.files_exists == 'false'
          && steps.check_package_lock.outputs.files_exists == 'false'
        run: npm install

      # run scripts
      - run: npm run lint --if-present
      - run: npm run test --if-present
      - run: npm run build --if-present

      # pre-build
      - name: Check .dockerignore
        id: check_dockerignore
        uses: andstor/file-existence-action@v1
        with:
          files: ".dockerignore"

      - name: Check dockerfile
        id: check_dockerfile
        uses: andstor/file-existence-action@v1
        with:
          files: "dockerfile"

      - name: Write .dockerignore
        if: steps.check_dockerignore.outputs.files_exists == 'false'
        run: echo "node_modules" > .dockerignore
      
      - name: Write dockerfile first part
        if: steps.check_dockerfile.outputs.files_exists == 'false'
        run: |
          echo FROM node:${{ matrix.node-version }}-alpine      >  dockerfile
          echo WORKDIR /app                                     >> dockerfile
          echo COPY . /app                                      >> dockerfile

      - name: Write dockerfile command yarn
        if: |
          steps.check_dockerfile.outputs.files_exists == 'false'
          && steps.check_yarn_lock.outputs.files_exists == 'true'
        run: echo RUN yarn                                      >> dockerfile

      - name: Write dockerfile command npm ci
        if: |
          steps.check_dockerfile.outputs.files_exists == 'false'
          && steps.check_package_lock.outputs.files_exists == 'true'
        run: echo RUN yarn                                      >> dockerfile

      - name: Write dockerfile command npm install
        if: |
          steps.check_dockerfile.outputs.files_exists == 'false'
          && steps.check_yarn_lock.outputs.files_exists == 'false'
          && steps.check_package_lock.outputs.files_exists == 'false'
        run: echo RUN npm install                               >> dockerfile

      - name: Write dockerfile last part
        if: steps.check_dockerfile.outputs.files_exists == 'false'
        run: |
          echo ENTRYPOINT [\"npm\"]                             >> dockerfile
          echo CMD [\"start\"]                                  >> dockerfile

      # build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Define image tags
        id: generate_docker_image_tags
        run: |
          DOCKER_IMAGE_TAGS="ghcr.io/${{github.repository}}:latest"
          DOCKER_IMAGE_TAGS="${DOCKER_IMAGE_TAGS}, ghcr.io/${{github.repository}}:d-${{needs.Setup.outputs.Date}}"
          DOCKER_IMAGE_TAGS="${DOCKER_IMAGE_TAGS}, ghcr.io/${{github.repository}}:b-${{needs.Setup.outputs.Branch}}"
          DOCKER_IMAGE_TAGS="${DOCKER_IMAGE_TAGS}, ghcr.io/${{github.repository}}:c-${{needs.Setup.outputs.ShaHash}}"
          DOCKER_IMAGE_TAGS="${DOCKER_IMAGE_TAGS}, ghcr.io/${{github.repository}}:t-${{needs.Setup.outputs.Timestamp}}"
          DOCKER_IMAGE_TAGS="${DOCKER_IMAGE_TAGS}, ghcr.io/${{github.repository}}:node-${{matrix.node-version}}"
          DOCKER_IMAGE_TAGS="${DOCKER_IMAGE_TAGS}, ghcr.io/${{github.repository}}:node-${{matrix.node-version}}-latest"
          DOCKER_IMAGE_TAGS="${DOCKER_IMAGE_TAGS}, ghcr.io/${{github.repository}}:node-${{matrix.node-version}}-d-${{needs.Setup.outputs.Date}}"
          DOCKER_IMAGE_TAGS="${DOCKER_IMAGE_TAGS}, ghcr.io/${{github.repository}}:node-${{matrix.node-version}}-b-${{needs.Setup.outputs.Branch}}"
          DOCKER_IMAGE_TAGS="${DOCKER_IMAGE_TAGS}, ghcr.io/${{github.repository}}:node-${{matrix.node-version}}-c-${{needs.Setup.outputs.ShaHash}}"
          echo "TAGS = ${DOCKER_IMAGE_TAGS}"
          echo "::set-output name=docker_image_tags::${DOCKER_IMAGE_TAGS}"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{steps.generate_docker_image_tags.outputs.docker_image_tags}}
          labels: "organization: ${{github.repository_owner}}, repository: ${{github.repository}}, branch: ${{needs.Setup.outputs.Branch}}, commit: ${{needs.Setup.outputs.ShaHash}}, date: ${{needs.Setup.outputs.Date}}, timestamp: ${{needs.Setup.outputs.Timestamp}}"

  Build-Python:
    runs-on: ubuntu-latest
    needs: Setup
    if: |
      github.event_name == 'push'
      && needs.Setup.outputs.RepositoryIsPython == 'true'

    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    
    steps:
      - uses: actions/checkout@v3

      - name: Pip install
        run: pip install -r requirements.txt
