name: service

on:
  workflow_call:
    outputs:
      firstword:
        description: "Repository main language"
        value: ${{ jobs.Setup.outputs.package_language }}

jobs:

  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check node repository
        id: check_node_repository
        uses: andstor/file-existence-action@v1
        with:
          files: "package.json"

      - name: Check python repository
        id: check_python_repository
        uses: andstor/file-existence-action@v1
        with:
          files: "requirements.txt"

      - if: steps.check_node_repository.outputs.files_exists == 'true'
        run: echo "::set-output name=package_language::node"

      - if: steps.check_python_repository.outputs.files_exists == 'true'
        run: echo "::set-output name=package_language::python"


  Install-Node:
    runs-on: ubuntu-latest
    needs: Setup
    if: ${{jobs.Setup.outputs.package_language == 'node'}}

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x, 17.x]
    
    steps:
      - uses: actions/checkout@v3

      - name: Check yarn.lock
        id: check_yarn_lock
        uses: andstor/file-existence-action@v1
        with:
          files: "yarn.lock"

      - name: Check package.lock
        id: check_yarn_npm
        uses: andstor/file-existence-action@v1
        with:
          files: "package.lock"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        if: steps.check_yarn_lock.outputs.files_exists == 'true'
        run: yarn

      - name: Npm ci
        if: steps.check_yarn_lock.outputs.files_exists == 'true'
        run: npm ci

      - run: npm run build --if-present
      
      - run: npm test --if-present

